version: '3.7'

services:
  #MYSQL
  mysql:
    image: mysql:latest
    container_name: hadoopmysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "local"
    volumes:
      - hadoop_mysql:/hadoop/mysql
      - "./scripts/huesetup.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./scripts/movielens.sql:/docker-entrypoint-initdb.d/2.sql"
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    networks:
      - hadoop

  #HADOOP MASTER
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.1.1-java8
    container_name: namenode
    ports:
      - 9870:9870
      - 8020:8020
    volumes:
      - ./${ADMIN_NAME}_home_on_namenode:/home/${ADMIN_NAME}
      - hadoop_namenode:/hadoop/dfs/name
      - ./overrides/namenode/entrypoint.sh:/entrypoint.sh
    env_file:
      - ./hadoop.env
      - .env
    networks:
      - hadoop

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.1.1-java8
    container_name: resourcemanager
    ports: 
      - 8088:8088
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864"
    env_file:
      - ./hadoop.env
    networks:
      - hadoop

  # HADOOP SLAVE 1
  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.1.1-java8
    container_name: datanode1
    volumes:
      - hadoop_datanode_1:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    networks:
      - hadoop

  nodemanager1:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.1.1-java8
    container_name: nodemanager1
    volumes: 
      - ./overrides/nodemanagers/entrypoint.sh:/entrypoint.sh
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
      - .env
    networks:
      - hadoop    

  # HADOOP SLAVE 2
  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.1.1-java8
    container_name: datanode2
    volumes:
      - hadoop_datanode_2:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    networks:
      - hadoop

  nodemanager2:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.1.1-java8
    container_name: nodemanager2
    volumes: 
      - ./overrides/nodemanagers/entrypoint.sh:/entrypoint.sh
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode2:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
      - .env
    networks:
      - hadoop    

  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.1.1-java8
    container_name: historyserver
    ports: 
      - 8188:8188
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 datanode2:9864 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
    networks:
      - hadoop

  # HUE
  filebrowser: 
    container_name: hue
    image: gethue/hue:4.4.0
    ports:
      - "8000:8888"
    env_file:
      - ./hadoop.env
    volumes: 
      - ./overrides/hue/hue-overrides.ini:/usr/share/hue/desktop/conf/hue-overrides.ini
      - ./overrides/hue/entrypoint.sh:/usr/share/hue/desktop/entrypoint.sh
      - hadoop_hue:/hadoop/hue
    depends_on:
      - namenode
      - resourcemanager
    networks:
      - hadoop
    command:
      - /usr/share/hue/desktop/entrypoint.sh

  # HIVE 
  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hiveserver
    env_file:
      - ./hadoop.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    networks:
      - hadoop 

  hive-metastore:
    container_name: hivemetastore
    image: bde2020/hive:2.3.2-postgresql-metastore
    env_file:
      - ./hadoop.env
    command: /opt/hive/bin/hive --service metastore
    networks:
      - hadoop
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 datanode2:9864 hive-metastore-postgresql:5432"

  hive-metastore-postgresql:
    container_name: hivedb
    image: bde2020/hive-metastore-postgresql:2.3.0
    networks:
      - hadoop

  presto-coordinator:
    container_name: presto
    image: shawnzhu/prestodb:0.181
    networks:
      - hadoop

  hbase:
    image: bde2020/hbase-standalone:1.0.0-hbase1.2.6
    container_name: hbase
    volumes:
      - ./overrides/hbase-master/entrypoint.sh:/entrypoint.sh
      - hbase_data:/hbase-data
      - hbase_zookeeper_data:/zookeeper-data
    ports:
      - 16000:16000
      - 16010:16010
      - 16020:16020
      - 16030:16030
      - 16040:16040
      - 16050:16050
      - 16060:16060
      - 16070:16070
      - 2888:2888
      - 3888:3888
      - 2181:2181
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 datanode2:9864"
    env_file:
      - ./hadoop.env
    networks:
      - hadoop
    command:
      - /entrypoint.sh

  oozie:
    image: equemuelcompellon/hadoop-oozie
    container_name: oozie
    volumes:
      - hadoop_oozie:/hadoop_oozie
      - ./overrides/oozie/entrypoint.sh:/entrypoint.sh
    ports:
      - 11000:11000
      - 11001:11001
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
      FS_DEFAULTFS: "hdfs://namenode:8020"
    networks:
      - hadoop
    command:
      - /entrypoint.sh

  ## ZOOKEEPER
  #zoo:
  #  image: zookeeper:3.4.10
  #  container_name: zoo
  #  environment:
  #    ZOO_MY_ID: 1
  #    ZOO_SERVERS: server.1=0.0.0.0:2888:3888
  #  ports:
  #    - 2181:2181
  #  networks:
  #    - hadoop

  ## HBASE
  #hbase-master:
  #  image: docker.io/bde2020/hbase-master:1.0.0-hbase2.4.5
  #  container_name: hbase-master
  #  hostname: hbase-master
  #  env_file:
  #    - ./hadoop.env
  #  volumes:
  #    - ./overrides/hbase-master/entrypoint.sh:/entrypoint.sh
  #    - hadoop_hbase:/hadoop/hbase
  #  environment:
  #    SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 datanode2:9864 zoo:2181"
  #  ports:
  #    - 16010:16010
  #    - 16040:16040
  #    - 16050:16050
  #    - 16060:16060
  #    - 16070:16060
  #  networks:
  #    - hadoop
  #  command:
  #    - /entrypoint.sh
#
  #hbase-region:
  #  image: docker.io/bde2020/hbase-regionserver:1.0.0-hbase2.4.5
  #  container_name: hbase-regionserver
  #  hostname: hbase-regionserver
  #  env_file:
  #    - ./hadoop.env
  #  environment:
  #    HBASE_CONF_hbase_regionserver_hostname: hbase-region
  #    SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 datanode2:9864 zoo:2181 hbase-master:16010"
  #  ports:
  #    - 16030:16030
  #  networks:
  #    - hadoop

networks:
  hadoop: 

volumes:
  hadoop_mysql:
  hadoop_namenode:
  hadoop_datanode_1:
  hadoop_datanode_2:
  hadoop_historyserver:
  hadoop_hue:
  #hadoop_hbase:
  hbase_data:
  hbase_zookeeper_data:
  hadoop_oozie:
